# fly.toml app configuration file generated for ribeirolabs-invoice-mysql on 2024-02-14T18:39:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ribeirolabs-invoice-mysql'
primary_region = 'gru'

[build]
image = 'mysql:8'

[env]
MYSQL_DATABASE = 'invoice'
MYSQL_USER = 'app'

[processes]
app = '--datadir /data/mysql --default-authentication-plugin mysql_native_password'

[mounts]
source = 'data'
destination = '/data'

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
